# Site settings
title: Nyle Sykes
description: Hi, I'm Nyle Sykes. I'm a MIT student studying computer science and finance. I am passionate about technology, media, and investing. Interested? Let's connect!
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Nyle Sykes
user_description: Hi, I'm Nyle Sykes. I'm a MIT student studying computer science and finance. I am passionate about technology, media, and investing. Interested? Let's connect!
user_title: MIT Computer Science and Finance Student
email: nsykes@mit.edu
twitter_username: nylesykes
github_username:  nsykes

exclude: ['package.json', 'src' , 'node_modules']
